
 

GET https://localhost:7216/api/voucher/all

###

GET https://lifepadi-v2-225229879541.us-east1.run.app/api/vendor/all

###

GET https://lifepadi-948405839190.us-east1.run.app/api/vendor/allActive


###

GET https://localhost:7216/api/vendorcategory/vendors/2

###
GET https://lifepadi-948405839190.us-east1.run.app/api/service/allActive


###
GET https://localhost:7216/api/address/all

###

GET https://lifepadi-v2-225229879541.us-east1.run.app/api/category/all

###

GET https://lifepadi-948405839190.us-east1.run.app/api/category/1/products?pageNumber=1&pageSize=5



###

PUT https://localhost:7216/api/address/setasdefault
Content-Type: application/json

{
    "CustomerId":20,
    "AddressId":80
}

###
GET https://localhost:7216/api/order/get/367

###
GET https://lifepadi-948405839190.us-east1.run.app/api/order/all

###
GET https://localhost:7216/api/order/customer/35?pageNumber=1&pageSize=5&SearchString=Ongoing

###
POST https://lifepadi-225229879541.us-east1.run.app/hubs/location/negotiate

###
POST https://lifepadi-948405839190.us-east1.run.app/hubs/notification/negotiate

###
POST https://lifepadi-948405839190.us-east1.run.app/api/notification
Content-Type: application/json

{
    "Title":"Small notification",
    "Message":"something something"
}

###
GET https://lifepadi-948405839190.us-east1.run.app/api/order/get/467

###

POST https://lifepadi-225229879541.us-east1.run.app/api/notification/general
Content-Type: application/json

{
    "Topic":"general",
    "Title":"WE ARE DELIVERING HAPPINESS TO FATHERS TODAY",
    "Body":"Fathers are unique, so also is Lifepadi. Deliver happiness to Dad using Lifepadi🥰"
}


###
POST https://lifepadi-948405839190.us-east1.run.app/api/location/rider
Content-Type: application/json

{
    "RiderId":"51",
    "Latitude":"6.3266352",
    "Longitude":"8.0957946"
}

###
GET https://lifepadi-948405839190.us-east1.run.app/api/walletDeposite/confirmDeposite?reference=LifePadi-krp7w0NuJV

###
GET https://lifepadi-948405839190.us-east1.run.app/api/wallet/transactions/8

###
GET https://lifepadi-948405839190.us-east1.run.app/api/transaction/paystack-confirmPayment?reference=LifePadi-UBjiMXRGS5


###
 PUT https://localhost:7216/api/rider/updateLocation/51
Content-Type: application/json

{
    "RiderId":"51",
    "Latitude":"6.3266352",
    "Longitude":"8.0957946"
}

###
 POST https://localhost:7216/api/walletwithdrawal/withdraw/8
Content-Type: application/json

{
    "WalletId":124,
    "Amount":"4000",
    "DeliveryFee":"1000",
    "TotalAmount":"5000",
    "OrderId":611,
    "Type":"Normal",
    "VoucherCode":"Lifepadi-bwrsiMxGoQ"
}

###
DELETE https://localhost:7216/api/address/delete/93


###
GET https://lifepadi-948405839190.us-east1.run.app/api/rider/51/getOrders?PageSize=10


###
GET https://localhost:7216/api/product/searchAll?SearchString=dr

###
POST https://lifepadi-948405839190.us-east1.run.app/api/customersupport/send
Content-Type: application/json

{
    "Subject":"Customer Support",
    "Message" : "This is customer support message"
}

###
POST https://lifepadi-948405839190.us-east1.run.app/chatHub/negotiate

###
GET https://localhost:7216/api/vendorcategory/vendors/2

###
GET https://lifepadi-225229879541.us-east1.run.app/api/vendor/all

###
POST https://lifepadi-948405839190.us-east1.run.app/api/customer/send-otp
Content-Type: application/json

{
    "PhoneNumber":"2348166932262"
}

###
PUT https://lifepadi-948405839190.us-east1.run.app/api/auth/password-reset
Content-Type: application/json

{
    "Email":"primeobjective@gmail.com",
    "NewPassword":"Esomchi"
}

###
GET https://localhost:7216/api/customer/orders/400

###
POST https://v3.api.termii.com/api/sms/otp/send
Content-Type: application/json

{
      "to": "2348138699452",
      "from": "N-Alert",
      "message_type": "NUMERIC",
      "channel": "dnd",
      "api_key": "TLGqtKdPOZZgZWuIrudhLMGErlxKKtqpIEWKYbOvXEsYaVYFEhWFzXHoUgUVrY",
      "pin_length": 4,
      "pin_placeholder": "< 1234 >",
      "message_text":"Your Lifepadi verification code is < 1234 >, it will expire in 5 minutes",
      "pin_attempts": 3,
      "pin_time_to_live": 5,
      "pin_type": "NUMERIC"
    }
###
GET https://localhost:7216/api/dashboard/dashboardStats

###
GET https://localhost:7216/api/vendor/all


###
GET https://localhost:7216/api/address/all



###
PUT https://localhost:7216/api/delivery/updatestatus/11?status=Completed
Content-Type: application/json

{
    "PhoneNumber":"2349030604334"
}

###
GET https://localhost:7216/api/googlemaps/addressfromplaceid?placeid=ChIJ5w1p-jehXBARMwg7ylaaXNI
###
GET https://localhost:7216/api/googlemaps/autocomplete?input=Dreamlink

###
GET https://localhost:7216/api/googlemaps/coordinates?address=Dreamlink Concepts, Abakaliki, Ebonyi State, Nigeria

###
GET https://lifepadi-225229879541.us-east1.run.app/api/delivery/getfee?Distance=5.7&DiscountPercentage=50
###
GET https://localhost:7216/api/delivery/getfee?Distance=5.7&DiscountAmount=500



