using Api.Models;
using Api.Validation;
using System.ComponentModel.DataAnnotations;

namespace Api.DTO
{
    public class CustomerDto
    {
        public int? Id { get; set; }
        [Required(ErrorMessage = "First name is required")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "First name must be between 2 and 50 characters")]
        [NameValidation(ErrorMessage = "First name contains invalid characters")]
        [NoHtmlValidation(ErrorMessage = "First name cannot contain HTML or script content")]
        public string? FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Last name must be between 2 and 50 characters")]
        [NameValidation(ErrorMessage = "Last name contains invalid characters")]
        [NoHtmlValidation(ErrorMessage = "Last name cannot contain HTML or script content")]
        public string? LastName { get; set; }
        [Required(ErrorMessage = "Email is required")]
        [StringLength(100, ErrorMessage = "Email cannot exceed 100 characters")]
        [EmailValidation(ErrorMessage = "Please enter a valid email address")]
        [NoHtmlValidation(ErrorMessage = "Email cannot contain HTML or script content")]
        public string? Email { get; set; }
        [Required(ErrorMessage = "Phone number is required")]
        [PhoneValidation(ErrorMessage = "Please enter a valid phone number (e.g., +1234567890)")]
        [NoHtmlValidation(ErrorMessage = "Phone number cannot contain HTML or script content")]
        public string? PhoneNumber { get; set; }
        [PasswordValidation(MinLength = 8, RequireUppercase = true, RequireLowercase = true,
                           RequireDigit = true, RequireSpecialChar = true,
                           ErrorMessage = "Password must be at least 8 characters and include uppercase, lowercase, a digit, and a special character")]
        public string? Password { get; set; }
        [StringLength(200, ErrorMessage = "Contact address cannot exceed 200 characters")]
        [NoHtmlValidation(ErrorMessage = "Contact address cannot contain HTML or script content")]
        public string? ContactAddress { get; set; }
        public string? RefreshToken { get; set; }
        public string? SearchString { get; set; }
        public bool? IsActive { get; set; }
        public WalletDto? Wallet { get; set; }
        public DateTime DOB { get; set; }
        [StringLength(6, MinimumLength = 6, ErrorMessage = "Referral code must be exactly 6 characters")]
        [RegularExpression("^[A-Z0-9]{6}$", ErrorMessage = "Referral code must contain only uppercase letters and numbers")]
        [NoHtmlValidation(ErrorMessage = "Referral code cannot contain HTML or script content")]
        public string? ReferredByCode { get; set; } // Code of the customer who referred this customer
        public string? ReferralCode { get; set; } // This customer's unique referral code (read-only, generated by system)
        public List<AddressDtoLite>? Addresses { get; set; }
        public List<OrderDtoLite>? Orders { get; set; }
        public List<CustomerVoucherDto>? CustomerVouchers { get; set; }
    }

    public class CustomerDtoLite
    {
        public int? Id { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? Email { get; set; }
        public string? PhoneNumber { get; set; }
        public string? Role { get; set; }
        public bool? IsActive { get; set; }
        public string? ContactAddress { get; set; }
        public DateTime DOB { get; set; }
        public WalletDto? Wallet { get; set; }
        public List<AddressDtoLite>? Addresses { get; set; }
    }

    public class AuthCustomerDto
    {
        public int Id { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? Email { get; set; }
        public string? PhoneNumber { get; set; }
        public string? ContactAddress { get; set; }
        public string? RefreshToken { get; set; }
        public string? AccessToken { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string? ReferralCode { get; set; } // This customer's unique referral code
        public WalletDto? Wallet { get; set; }
    }

    public class CheckUserExistsDto
    {
        [PhoneValidation(ErrorMessage = "Please enter a valid phone number")]
        [NoHtmlValidation(ErrorMessage = "Phone number cannot contain HTML or script content")]
        public string? PhoneNumber { get; set; }

        [EmailValidation(ErrorMessage = "Please enter a valid email address")]
        [NoHtmlValidation(ErrorMessage = "Email cannot contain HTML or script content")]
        public string? Email { get; set; }
    }
}
