name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # Change this to your default branch if it's not 'main'

env:
  PROJECT_ID: lifepadi-443208
  REPOSITORY: us-east1-docker.pkg.dev/lifepadi-443208/lifepadi-repo/lifepadi
  SERVICE_NAME: lifepadi
  REGION: us-east1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SE_SECRET }}

    - name: Authenticate Docker to GCP Artifact Registry
      run: |
        echo "${{ secrets.GCP_SE_SECRET }}" > sa-key.json
        gcloud auth activate-service-account --key-file=sa-key.json
        gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

    - name: Build Docker image
      working-directory: ./Web/Api  # Change to the directory containing the Dockerfile
      run: |
        docker build -t ${{ env.REPOSITORY }}:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push ${{ env.REPOSITORY }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.REPOSITORY }}:${{ github.sha }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated